pipeline {
    agent any
    // agent {
    //     docker { 
    //         image 'alpine3.19'
    //         registryUrl 'https://hub.docker.com/_/node'
    //         label docker-agent

    //          }
    // }

    stages {
        stage('build Dockerfile') {

            steps {
                sh '''echo "FROM maven:3-alpine
                          RUN apk add --update docker openrc
                          RUN rc-update add docker boot" >/var/lib/jenkins/workspace/Dockerfile'''

            }
         }

         stage('run Dockerfile') {
             agent{
                 dockerfile {
                            filename '/var/lib/jenkins/workspace/Dockerfile'
                            args '--user root -v $HOME/.m2:/root/.m2  -v /var/run/docker.sock:/var/run/docker.sock'
                        }
             }

             steps {
                 sh 'docker version'
                 sh 'mvn -version'
                 sh 'java -version'
             }

         }
        stage('Run App Tests') {
            steps {
                sh '''
                    pip install npm
                    CI=true npm run test
                   '''
            }
    }}
    triggers {
        pollSCM('') //Empty quotes tells it to build on a push
    }
    
}