pipeline {
    agent docker-agent
    // agent {
    //     docker { image 'node:20.11.1-alpine3.19' }
    // }

    stages {
        stage('Run App Tests') {
            steps {
                sh '''
                    pip install npm
                    CI=true npm run test
                   '''
            }
    }}
    triggers {
        pollSCM('') //Empty quotes tells it to build on a push
    }
    
}